### ISSUE TITLE
Hotjar integration

### ISSUE THREAD

**Issue by bittner** [jcassee/django-analytical#103]
Should we consider integrating [Hotjar](https://www.hotjar.com)?

Documentation
----------------

- [Hotjar tracking code](https://docs.hotjar.com/docs/hotjar-tracking-code)
- [What is Hotjar?](https://docs.hotjar.com/docs/what-is-hotjar)

**Comment by dufrenb** [comment]
Hello!
Does Hotjar integration still planned?

**Comment by bittner** [comment]
@dufrenb Thanks for asking!

It's the other way round, though. If you want Hotjar integration please consider placing a pull request. Or [bug the Hotjar team](https://www.hotjar.com/contact) to do it for you in this repository. There is no such thing as a free lunch.

**Comment by dufrenb** [comment]
@bittner 
I was searching to use an analytical service in a web site for a client so I switch to use Clicky.
I think have Hotjar integrated as the others here: https://pythonhosted.org/django-analytical/services.html could be very good idea!

**Comment by bittner** [comment]
I agree. If you want to have it added to the list, come the repository, look at the code and write your implementation of the integration. It's not difficult to do.

We don't get paid, neither for promoting not for implementing integrations. Hence, it depends on the popularity of a service and the needs of our users (Django developers who like this app). If you feel it's missing add it to the code base. Our ask Hotjar, they may (or may not) care.

**Comment by jcassee** [comment]
Fixed by #137
