### ISSUE TITLE
Any support planned for the newer Google analytics.js library?

### ISSUE THREAD

**Issue by qurm** [jcassee/django-analytical#108]
Hi team,

I see that the ga.js, has been replaced by a later library, and that is recommended for new implementations.  Would be great if you are able to support that also, perhaps in parallel to the ga.js for some time.
https://developers.google.com/analytics/devguides/collection/gajs/

Thanks for all your good work with djang-analytical,
Andy

**Comment by jcassee** [comment]
Thanks for the heads-up! The JavaScript snippets are really just strings in Python sources. Do you think you could submit the changes yourself in the form of a pull request?

**Comment by jcassee** [comment]
Merged #135
