### ISSUE TITLE
Support Django 2.0

### ISSUE THREAD

**Issue by Anteru** [jcassee/django-analytical#120]
Django 2.0 breaks `if user.is_authenticated():` (utils.py, line 74), which needs to become `if user.is_authenticated:` -- this should also work from Django 1.10 onwards, see: https://docs.djangoproject.com/en/2.0/releases/1.10/#using-user-is-authenticated-and-user-is-anonymous-as-methods

**Comment by bittner** [comment]
Would you mind to prepare a PR?

**Comment by Anteru** [comment]
PR added.

**Comment by Anteru** [comment]
Guess this can be closed then, given the PR has been merged. Hope you'll push out a release soon :)

**Comment by bittner** [comment]
Thanks @Anteru!
