### ISSUE TITLE
Can I fetch and Display Analytic reports?

### ISSUE THREAD

**Issue by Leo-G** [jcassee/django-analytical#122]
I want to fetch the top posts on my blog based on monthly views and display them on the sidebar, I am not sure if I can do that using django-analytical, can someone confirm?

**Comment by bittner** [comment]
If I read your question right I'm afraid this is not what you get from django-analytical. This package is about integrating analytics services cleanly, and this typically refers to the data _collection_ feature of those services.

That said, if _"fetch the top posts on my blog based on monthly views"_ is supported by any service you know you may be able to use that with this package. The _"display them on the sidebar"_ is more what you wouldn't get out-of-the-box.

That said, this doesn't stop you from making a pull request to add a new template tag to an analytics service that supports that kind of feature. As long as this all is in line with "[keeping your template clean](https://django-analytical.readthedocs.io/en/latest/#overview)" there should be room for that code in this project.

Feel free to reopen this issue for further clarification or place a pull request for feature enhancements!
