### ISSUE TITLE
Does the library support Intercom Events?

### ISSUE THREAD

**Issue by charleshan** [jcassee/django-analytical#136]
it's not mentioned in the [documentation](https://django-analytical.readthedocs.io/en/latest/services/intercom.html) so I'm guessing that it may not yet have been implemented.

You can read more about event tracking in intercome here: 
https://www.intercom.com/help/configure-intercom-for-your-product-or-site/customize-intercom-to-be-about-your-users/set-up-event-tracking-in-intercom

**Comment by bittner** [comment]
Short answer: Yes, probably - if Intercom does.

Long answer: Everything django-analytical does is abstract away the JavaScript snippet pasting into your Django templates.

You may want to verify if the [implementation in the module](https://github.com/jcassee/django-analytical/blob/master/analytical/templatetags/intercom.py#L18-L21) still matches the instructions provided by Intercom. If not, a PR is always welcome.
