### ISSUE TITLE
RFC: python3 support (which would mean dropping atleast 2.5)

### ISSUE THREAD

**Issue by tinnet** [jcassee/django-analytical#24]
Hi, since django 1.5 was just released with preliminary python 3 support, i think it's a good time to discuss what python3 support would mean for this app.

There are pieces of code that simply are impossible to do in a way that is supported from python2.5 up to 3.3 :( e.g. exception handling (http://stackoverflow.com/questions/11285313/try-except-as-error-in-python-2-5-python-3-x)

What are your thoughts about this? Is dropping python < 2.7 support even worth considering?

**Comment by jcassee** [comment]
Fixed by @amadornimbis in #52, merged as aab1cfc508040ea87593e48b4d266800ba568635 and release as 0.21.0.
