### ISSUE TITLE
Clickmap doesn't work with new ID's

### ISSUE THREAD

**Issue by delta440** [jcassee/django-analytical#51]
My guess is clickmap changed their ID format because mine looks like WVXXXWX5UGKXXX0F16021157XXI3PYX8 and your code seems to have a check in place to only accept a numeric ID

**Comment by delta440** [comment]
After the following changes:
- CLICKMAP_TRACKER_ID_RE = re.compile(r'^\d+$')
+CLICKMAP_TRACKER_ID_RE = re.compile(r'^\S+$')

-                "must be a (string containing) a number")
+                "must be an alphanumeric string")
I received a 'ClickmapNode' object has no attribute 'portal_id' error

**Comment by jcassee** [comment]
Thanks, I'll change this shortly.

**Comment by jcassee** [comment]
Fixed in e44141be803a4a9b3adeaee9d61cea605d7cb245.
