### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hobarrera** [jcassee/django-analytical#72]
It's been a while since the last release, and the latest `master` crashes with django19 (which is at rc, and will be release in less than a couple of weeks).

Can we get a new release (1.0.1?), that's django19-compatible? :)

**Comment by bittner** [comment]
All our builds are passing. As long as Django 1.9 is not stable don't expect it to be added to the build matrix.

What is crashing? Can you post a stack trace? Can you provide a PR?

**Comment by hobarrera** [comment]
Django 1.9 has already been stabilized, and is currently on rc1.

`master` works with django1.9, but the latest release isn't working, that why I was merely mentioning a new release and didn't give much more details. :D  
Notably, 87bb09c fixes a deprecation from 1.7 that no longer works on 1.9, but that didn't make it into 1.0.0.

**Comment by bittner** [comment]
I'd recommend you add 1.9 to the [build matrix](https://github.com/jcassee/django-analytical/blob/master/tox.ini), and we see what happens. If all goes well with the code as it is. Your PR is appreciated.

As soon as 1.9 is officially out we'll merge that into `master` and package a release, I'd suppose.

**Comment by hobarrera** [comment]
I've added 1.9 to the dependency matrix (along with py35 which was also missing, and has been release for some time now).

Hopefully this can be merged in and a new release can be made? :D

**Comment by brainrape** [comment]
bump

**Comment by bittner** [comment]
@brainrape See [our Gitter chat](https://gitter.im/jcassee/django-analytical). Joost must take a decision on the version number. We're getting there.

**Comment by brainrape** [comment]
Thanks

**Comment by jcassee** [comment]
Finally release version 2.0.0 that is compatible with 1.9 thanks to @hobarrera.
