### ISSUE TITLE
PIWIK_DOMAIN_PATH regex forbids 'localhost/piwik'

### ISSUE THREAD

**Issue by mkane848** [jcassee/django-analytical#76]
While I got around the issue by using  `PIWIK_DOMAIN_PATH = '127.0.0.1/piwik' `, I get the Exception of `PIWIK_DOMAIN_PATH setting: must be a domain name, optionally followed by an URI path, no trailing slash (e.g. piwik.example.com or my.piwik.server/path)` if I have it just set as localhost/piwik. I assume that `^(([^./?#@:]+\\.)+[^./?#@:]+)+(/[^/?#@:]+)*$` wants to see a '.' in there somewhere :P

**Comment by bittner** [comment]
Exactly, the [regular expression](https://github.com/jcassee/django-analytical/blob/master/analytical/templatetags/piwik.py#L17) looks for a minimum of a `<domain>.<tld>` expression.

Can you explain why a private host makes sense in the context of Piwik? If a page in the browser is loaded then `localhost` would try to access a a resource local to the calling agent. Are you sure you want that?

## Proposed change

Can you try changing the `+` after the first group to a `*` in [DOMAINPATH_RE](https://github.com/jcassee/django-analytical/blob/master/analytical/templatetags/piwik.py#L17) as follows, and confirm that this allows `localhost`?
````python
# domain name (characters separated by a dot), optional URI path, no slash
DOMAINPATH_RE = re.compile(r'^(([^./?#@:]+\.)*[^./?#@:]+)+(/[^/?#@:]+)*$')
```

**Comment by mkane848** [comment]
Confirmed that the new regex allows localhost, thanks! Using it for the sake of local testing to try it out, thanks for the help
