### ISSUE TITLE
Remove obsolete Reinvigorate.net support

### ISSUE THREAD

**Issue by KaySackey** [jcassee/django-analytical#82]
Reinvigorate.net closed about a year ago, so it should be removed from this project.

**Comment by jcassee** [comment]
Thanks for the heads-up. I'll remove it.

**Comment by bittner** [comment]
Additional clarification: Reinvigorate has not gone out of business, they have been bought by [Webtrends](http://www.webtrends.com/).

Unfortunately, this doesn't really change the fact that it needs to be removed from the code base. Integration docs are difficult to find, and it looks like their service is not even popular.

## References

* [Last notes on their Facebook account](https://www.facebook.com/reinvigorate) (19 Dec 2011)
* [Webtrends buys Reinvigorate](http://techcrunch.com/2011/08/08/webtrends-buys-media-temple-backed-realtime-analytics-firm-reinvigorate/) (TechCrunch, 08 Aug 2011)

## Resources

* [Webtrends Product Help](http://producthelp.webtrends.com/) (Infinity Analytics)
* [Description and alternatives](http://alternativeto.net/software/webtrends/)
